sources:
  - name: horizon-polygon-mumbai
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/yuriarthf/horizon-testnet-mumbai
documents:
  - ./src/get-iros-by-status.graphql
  - ./src/get-iros-by-id.graphql
  - ./src/get-iro.graphql
  - ./src/get-user-shares.graphql
  - ./src/get-real-estate-account.graphql
